import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import type { BuildInfo } from './types'

/**
 * Build identity.
 *
 * `build-info.json` is generated by the release pipeline (`npm run build:info`) and packaged with the
 * application, so the About screen can show exactly which version, commit and toolchain produced the
 * installed copy. In development the values come from `package.json` and the running Electron
 * process, and unknown fields are reported as "unknown" rather than invented.
 */

interface BuildInfoFile {
  version?: string
  buildNumber?: string
  gitSha?: string
  builtAt?: string
}

function safeRead(path: string): BuildInfoFile | null {
  try {
    if (!existsSync(path)) return null
    return JSON.parse(readFileSync(path, 'utf8')) as BuildInfoFile
  } catch {
    return null
  }
}

export function readBuildIdentity(options: { appRoot: string, isPackaged: boolean, resourcesPath: string | null }): BuildInfo {
  const candidates = [
    options.resourcesPath ? join(options.resourcesPath, 'build-info.json') : null,
    join(options.appRoot, 'build-info.json'),
    join(options.appRoot, '..', 'build-info.json')
  ].filter((entry): entry is string => entry !== null)

  let file: BuildInfoFile | null = null
  for (const candidate of candidates) {
    file = safeRead(candidate)
    if (file) break
  }

  let fallbackVersion = '0.0.0'
  try {
    const pkg = JSON.parse(readFileSync(join(options.appRoot, 'package.json'), 'utf8')) as { version?: string }
    fallbackVersion = pkg.version ?? fallbackVersion
  } catch {
    /* packaged builds always carry build-info.json; the fallback is only for a broken install */
  }

  return {
    version: file?.version ?? fallbackVersion,
    buildNumber: file?.buildNumber ?? (options.isPackaged ? 'unknown' : 'dev'),
    gitSha: file?.gitSha ?? 'unknown',
    builtAt: file?.builtAt ?? 'unknown',
    electron: process.versions.electron ?? 'unknown',
    chromium: process.versions.chrome ?? 'unknown',
    node: process.versions.node
  }
}
